League-central/curriculum

levels/Level4/Mod2Recipes/index.html

Link was creating repos in league-level4 when it was supposed to be league-level4-student. Took the link from the overview page which works.

Fixed the github repo link

---

levels/Level0/modules/Mod1Recipes/forLoopSelfTest.html

Minor change - Often means frequently and does not have  a count connotation.  Changing "often" >> "many times" is better wording.

Minor Semantical Change

---

levels/Level4/Mod0Recipes/2D Array Quiz 2.html

Range of sequential numbers should be from 0-8, (not 0-9) which are a total of 9 numbers.
int[][] mat3 = new int[3][3];
for(int i = 0; i < mat3.length; i++){
for(int j = 0; j < mat3.length; j++){
/*ANSWER GOES HERE*/
}
}
Answer: D
mat3[i][j] = i * mat3[i].length + j;

Incorrect range of numbers in Question 1

---

levels/Level4/Level4 Overview.html

Links here pointed to old version of this assignment which I have since removed from classroom. Cleaned up and updated with a new bitly and classroom link

Update Level4 Overview.html

---

levels/Level4/Level4 Teachers.html

Updating teacher's page for new links like I did for overview of level 4 module 2.

Update Level4 Teachers.html

---

levels/Level0/Module5/index.html
levels/Level0/Recipes/StudentSummary.html
levels/Level0/Recipes/studyColor.html
levels/Level0/Recipes/studyForLoop.html
levels/Level0/Recipes/studyGuideIndex.html
levels/Level0/Recipes/studyIfElse.html
levels/Level0/Recipes/studyIncrement.html
levels/Level0/Recipes/studyJOptionPane.html
levels/Level0/Recipes/studyMainMethod.html
levels/Level0/Recipes/studyMethods.html
levels/Level0/Recipes/studyModulo.html
levels/Level0/Recipes/studyRandom.html
levels/Level0/Recipes/studyRobot.html
levels/Level0/Recipes/studyString.html
levels/Level0/Recipes/studySyso.html
levels/Level0/Recipes/studyVariables.html

Modified the Level 0 study guide:
1. Added more subject areas for completeness
2. Broke up into specific topics for easier reading and future maintenance
3. Added links to the study guide from the student summary page

L0 study guide

---

levels/Level1/Mod4Recipes/WhackAMole.html

Updated L1 M4 speak method code in Whack A Mole.

Updated speak method

---

levels/Level0/Level0Grading.html
levels/Level0/Module0/module0SelfTest.html
levels/Level0/Module1/module1SelfTest.html
levels/Level0/Module2/module2SelfTest.html
levels/Level0/Overview_L0.html
levels/Level0/index.html

Added new Socrative quiz links as checkpoints for Modules 0 through 4
Added new Socrative quiz links for Practice Tests 1 and 2 in Module 5 checkpoint
Added new Grading Assistant to match new written exam format.
NOTE: An update of Level 0 exam link is required to match this version of Grading Assistant.

Level 0 checkpoint updates

---

levels/Level0/Module3/index.html
levels/Level0/Recipes/loopVarSelfTest.html
levels/Level0/Recipes/moduloSelfTest.html

else if, loop variable, and modulo self tests added to module 3.

Self Tests added to L0M3

---

levels/Level0/Recipes/whatOutput.html

The script for checking answers was not moved in recent restructure of Level0. Put Javascript into html file so they will stay together moving forward.

Fix: answer check scripts added

---

levels/Level1/Mod2Recipes/TeaParty.html

I separated tests so that students hopefully clearly see which tests they are failing or passing. I also added an additional test for women who have achieved damehood. 
In the future, we could also add some randomized tests to ensure the students are using the correct logic in their method.

Additional Tea Party tests

---

levels/Level0/Recipes/Pizza.html

NOTE: This should only be moved to Master when the corresponding module update is released, since it refers to the images that have been added to the pizza code folder.

Reword toppings section

---

levels/Level0/Recipes/FlamingNinjaStar.html
levels/Level0/Recipes/My Ages.html
levels/Level0/Recipes/PentagonCrazy.html
levels/Level0/Recipes/RobotSpiral.html
levels/Level0/Recipes/RobotSquare.html
levels/Level0/Teachers_L0.html

Change all loop references in Module 0 recipes to simply state "loop", now students will start with while loops. MyAges (Module 1)  now introduces students to for loops.

L0 while loops first

---

levels/Level0/Teachers_L0.html

Page was out of date with current Level0 content

Update Teacher Overview to reflect current content

---

levels/Level1/Level1 Overview.html
levels/Level1/Mod3Recipes/index.html

Added Robot in a Jar recipe to overview and L1M3 index.

L1 intro to jars

---

levels/Level5/Overview_L5.html

Socrative checkpoints have been added to the Overview page

added socrative checkpoints for mods 0 - 3

---

levels/Level2/GameProject/level2_demos.html

Added a demo to league-level2 that shows students how to make projectiles fly towards that mouse cursor. This is a popular request from students.

Better Projectiles Demo

---

levels/Level3/Level3 Students.html

level3.jointheleague.org redirects to this html page with spaces in the url and I don't know where to find the redirect source.

old redirected html page

---

levels/Level1/Mod0Recipes/JackInTheBox.html
levels/Level1/Mod0Recipes/SensitiveKeyboard.html
levels/Level1/Mod0Recipes/SoundEffects.html

Updated Sound Effects and Jack in the Box to use the Clip class in place of the deprecated AudioClip.
Also put the new speak () method in the SensitiveKeyboard recipe for MS Windows users.

L1 m0 audio clip replace

---

levels/Level3/Mod0Recipes/index.html
levels/Level3/Mod3Recipes/index.html

To match code in /java-modules

Add regex and 2D array practice to web pages

---

levels/Level0/Module3/index.html
levels/Level0/Overview_L0.html
levels/Level0/Recipes/Bullseye.html
levels/Level0/Recipes/Bumblebee.html
levels/Level0/Recipes/FizzBuzz.html
levels/Level0/Recipes/remainder.html
levels/Level0/Recipes/remainderSelfTest.html
levels/Level0/Teachers_L0.html

Updated any spot in level0 that said "modulo" to say "remainder"

L0 remainder

---

levels/Level0/Module3/extras.html
levels/Level0/Module3/index.html
levels/Level0/Module5/index.html
levels/Level0/Overview_L0.html
levels/Level0/Recipes/Bullseye.html
levels/Level0/Recipes/Bumblebee.html
levels/Level0/Recipes/FizzBuzz.html
levels/Level0/Recipes/remainder.html
levels/Level0/Recipes/remainderSelfTest.html
levels/Level0/Teachers_L0.html

Removed the Houses recipe links in l0m3 extras and l0m5

L0 remove houses recipe

---

levels/Level1/Mod1Recipes/vault.html

Updating the instructions to Vault. Since this is the first time the student will make a class that's not the Runner, the Vault class will now be given and the goal will be to create the SecretAgent class and a Runner

L1M1 - Update vault.html

---

levels/Level1/Level1 Overview.html
levels/Level1/Mod1Recipes/index.html

Tied to PR: https://github.com/League-central/java-modules/pull/287

Add Hungry Hungry Hippos

---

levels/Level1/Level1 Overview.html
levels/Level1/Mod1Recipes/index.html

Added Asteroids to the list of recipes

L1M1 - Matching Curriculum to recipe

---

Tier3Overview.html
index.html
levels/Level6/index.html
studentIndex.html
teacherIndex.html

also fix a few broken links and typos

Add level descriptions to teacher and student index

---

levels/Level0/Recipes/99Bottles.html
style/style.css

- 99 Bottles is not an officially listed module, it is only available by going directly to the URL.
- I'm hoping to improve the look and feel of the early level (0-3) modules.
- Starting with an unlisted module seems like a good way to test some ideas and get feedback.
Before:
After:

improve look of 99Bottles
